name: CI/CD Helm Chart + Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio de la aplicación
      - name: Checkout application repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js (si la app lo requiere)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Build y push de la imagen Docker
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: andrea233/delivery-system
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ------------------------------
      # 4. Clonar el repositorio del Helm Chart (fuente)
      - name: Checkout Helm chart repository
        uses: actions/checkout@v3
        with:
          repository: AndreSosa21/chartsHelm-delivery-app
          path: helm-repo

      # 5. Clonar el repositorio de GitHub Pages (donde se publican los charts)
      - name: Checkout Helm Pages repository
        uses: actions/checkout@v3
        with:
          repository: AndreSosa21/chartsHelm-delivery-app
          token: ${{ secrets.GITHUB_TOKEN }}
          path: helm-pages

      # 6. Debug: ver estructura de los repositorios
      - name: Debug - List repos
        run: |
          echo "Helm source repo:"
          ls -R helm-repo
          echo "Helm Pages repo:"
          ls -R helm-pages

      # 7. Empaquetar chart Helm dentro del repo de Pages
      - name: Package Helm chart
        run: |
          helm package helm-repo/delivery-app/delivery-app --destination helm-pages

      # 8. Actualizar index.yaml dentro del repositorio de Pages
      - name: Update Helm repo index
        run: |
          cd helm-pages
          if [ -f index.yaml ]; then
            helm repo index . --url https://andreSosa21.github.io/chartsHelm-delivery-app/ --merge index.yaml
          else
            helm repo index . --url https://andreSosa21.github.io/chartsHelm-delivery-app/
          fi

      # 9. Subir charts y index.yaml al repo de GitHub Pages
      - name: Deploy Helm chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-repo/helm-packages