name: CI/CD Helm Chart + Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Mostrar estructura para debug
      - name: Show repo structure
        run: ls -R

      # 3. Configurar Node.js si lo necesitas
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4. Build y push de la imagen Docker
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: andrea233/delivery-system
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Empaquetar chart Helm
      - name: Package Helm chart
        run: |
          mkdir -p helm-packages
          helm package delivery-app/delivery-app --destination helm-packages

      # 6. Actualizar index.yaml
      - name: Update Helm repo index
        run: |
          helm repo index helm-packages --url https://andresosa21.github.io/chartsHelm-delivery-app/

      # 7. Subir los charts empaquetados a GitHub Pages
      - name: Deploy Helm chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm-packages
